### ISSUE TITLE
Confused on when to use this Action

### ISSUE THREAD

**Issue by yucwan** [Azure/cli#11]
Since you can directly run az command with `run`, like:
```
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    ...
    - name: AZ CLI commands
          run: |
            az account show
```
I'm confused when should I use this Action for Azure CLI? to use a specific CLI version? or for platforms without az installed?
