### ISSUE TITLE
Azure/CLI@V1 Error on Self-Hosted Runner on Azure AKS

### ISSUE THREAD

**Issue by moulidz** [Azure/cli#116]
Hi, 

I am facing an error while using Azure/CLI@V1 on my self-hosted runner on Azure Kubernetes Service. 

The error: 
ERROR: Please run 'az login' to setup account.
Error: Error: az cli script failed.

CLi version: 2.52.0 pre-installed on the AKS actions-runner image along with Azure powershell modules. 

The Azure/Login@V1 is successful and Azure/Powershell@V1 is also successful. Only the Azure/CLI@V1 has the error. 

On inspecting the docker image for the CLI, I found that the .azure folder is empty. 

![image](https://github.com/Azure/cli/assets/132992564/352d611d-0c7c-4b51-8096-7c296bba6312)

When I run the same workflow on an Azure VM self-hosted runner instead of AKS, the Azure/CLI@V1 works and it is the same version - 2.52.0

![image](https://github.com/Azure/cli/assets/132992564/f07133fd-1c2e-4ae4-8a28-c7397f57fb3b)

Is the error because of the latest version of CLI? Should I revert to 2.30.0?

Thanks
Mouli

**Comment by MoChilia** [comment]
Hi @moulidz,
Sorry for the delay. This issue could be due to docker incorrectly mounting the `.azure` folder created by the azure/login action. From my understanding, this issue is specific to self-hosted runners in AKS and appears to be a bug in the azure/cli action, unrelated to the Azure CLI version. I'll need some time to investigate and resolve this. Thank you for your patience.

**Comment by moulidz** [comment]
Hi @MoChilia,

Sure. I will also test on my side with different configurations and update here if i find anything.

**Comment by spowser** [comment]
This may be related but I am also getting an error when running the agent from an attached disk in Azure.  The agent runs on a Linux VM from a mounted drive at `/mnt/blah/whatever/action-runner`.  The error I'm seeing is 

```
Starting script execution via docker image mcr.microsoft.com/azure-cli:2.57.0
Error: Error: docker: Error response from daemon: create undefined/.azure: "undefined/.azure" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
```

Hope this helps either reproduce it or narrow down the root cause

**Comment by moulidz** [comment]
Hi, 

I tried the az cli action from a new self-hosted runner using the github arc runner. Got a different error here:

`Starting script execution via docker image mcr.microsoft.com/azure-cli:2.57.0
Error: Error: docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.`

Thanks
mouli

**Comment by vijayrajah** [comment]
I face the same issue with `azure/login@v2`

for the workaround, I'm installing azure cli on every action run & using it

**Comment by MoChilia** [comment]
Hi @vijayrajah, you can try running `az login` inside `azure/cli` instead of `azure/login`.
```yaml
    - name: Azure CLI Action
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
           az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
           az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
```

**Comment by MoChilia** [comment]
I see the issue. This is tricky. Most GitHub Actions users deploy self-hosted runners on Kubernetes using [actions/actions-runner-controller](https://github.com/actions/actions-runner-controller). By default, this controller mounts `/run`, `/runner`, and `/runner/_work` as volumes to both the runner and docker containers ([see this function](https://github.com/actions/actions-runner-controller/blob/ad2dd7d787a8f6200aa33eea6ebf87981e699d73/controllers/actions.summerwind.net/runner_controller.go#L772)).

You can verify these mounts by running:
 ```
kubectl describe pod {your-gha-runner-pod} -n {pod-namespace}
```

You’ll see output similar to:
```
Containers:
  runner:
    Mounts:
      /run from var-run (rw)
      /runner from runner (rw)
      /runner/_work from work (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-xxx (ro)
  docker:
    Mounts:
      /run from var-run (rw)
      /runner from runner (rw)
      /runner/_work from work (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-xxx (ro)
```

However, the home directory (`$HOME`), which defaults to `/home/runner` (see [Dockerfile line](https://github.com/actions/actions-runner-controller/blob/ad2dd7d787a8f6200aa33eea6ebf87981e699d73/runner/actions-runner.ubuntu-24.04.dockerfile#L40)), is not mounted.

This matters because the Azure CLI stores login information in the `AZURE_CONFIG_DIR`, which is `$HOME/.azure` by default. The Azure login action uses the same directory, and the Azure CLI action tries to mount it into the Docker container to access authentication details. But since `$HOME` isn’t mounted into the docker container, the Azure CLI action cannot access the Azure config directory as expected.

To solve this issue, there are four solutions
1. **Volume mount `$HOME` for Docker in the runner deployment spec**
Add a shared volume for `/home/runner` to both runner and docker containers:
```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: gha-test-runner
  namespace: actions-runner-system
spec:
  replicas: 2
  template:
    spec:
      repository: org/repo
      volumeMounts:  
        - name: home-runner
          mountPath: /home/runner
      volumes:
        - name: home-runner
          emptyDir: {}
      dockerVolumeMounts:
        - name: home-runner
          mountPath: /home/runner
```
2. **Change `$HOME` in the runner deployment spec**
Set the HOME environment variable to a directory that is already mounted:
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: gha-test-runner
  namespace: actions-runner-system
spec:
  replicas: 2
  template:
    spec:
      repository: org/repo
      env:
        - name: HOME
          value: /runner/home
```
3. **Change `$AZURE_CONFIG_DIR` in workflow**
Override the default config path for both Azure/login and Azure/cli:
```
- name: Azure CLI login
        uses: azure/login@v2
        env: 
            AZURE_CONFIG_DIR: "/runner/.azure"
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Azure CLI script
        uses: azure/cli@master
        env: 
            AZURE_CONFIG_DIR: "/runner/.azure"
        with:
          azcliversion: latest
          inlineScript: |
            az account show
```
4. **Run `az login` within Azure cli action**
This approach doesn't require pre-installed Azure CLI. See examples in https://github.com/Azure/cli/issues/116#issuecomment-2567236699.

If you’re not using actions-runner-controller for your GitHub Actions runners, you can still use `kubectl describe pod` to troubleshoot. Ensure that the HOME directory is mounted in the Docker container.
