### ISSUE TITLE
Pre Azure Login is getting added and GitHub actions is failing

### ISSUE THREAD

**Issue by wulfnb** [Azure/cli#131]
In GitHub actions, I'm using Azure Login.

But 4 hours ago its getting added Pre Azure Login and Post Azure login and its failing.

```
    - name: Azure login
      uses: Azure/login@v1
      with:
        creds: 
```

<img width="1305" alt="Screenshot 2024-01-16 at 6 24 43 PM" src="https://github.com/Azure/cli/assets/46603705/14fed876-c6c8-45b1-9b2e-f869987a3493">

<img width="1305" alt="Screenshot 2024-01-16 at 6 28 16 PM" src="https://github.com/Azure/cli/assets/46603705/848f2e3f-a5f3-4bb5-a88d-ffe41c9650ed">
