### ISSUE TITLE
📢 Azure/cli v2 Release Announcement

### ISSUE THREAD

**Issue by MoChilia** [Azure/cli#143]
👀 **What’s new in `azure/cli@v2`?**

- The default runtime of `azure/cli` is updated from `Node16` to `Node20` due to [the upcoming deprecation of Node16](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/).

⚠️ **This is breaking change**

- If you're using `azure/cli` with a self-hosted runner, ensure it's running [Actions Runner image v2.308.0](https://github.com/actions/runner/releases/tag/v2.308.0) or later.

To apply this change, please update the version of `azure/cli` to `v2` in your workflow files.
```yaml
    - name: Run Azure CLI Action
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az version
```
