### ISSUE TITLE
 azure/login@v2 action in workflow just runs and never completes on pre login using private networking with GitHub-hosted runner

### ISSUE THREAD

**Issue by stan-spotts** [Azure/cli#149]
Following directions at [Configuring private networking for GitHub-hosted runners in your organization](https://docs.github.com/en/organizations/managing-organization-settings/configuring-private-networking-for-github-hosted-runners-in-your-organization), I manually kicked off a workflow to push a set of services in node.js to an image in an azure container registry. It won't get past a "pre login" step (that it adds itself). Raw logs say the job is about to start.  It appears the configuration is okay, as NIC's from GitHub appear in my resource group.

The workflow up to this point is simply this:

```
on: 
    workflow_dispatch:
    #[push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: LinuxRunner

        steps:
        - name: Log Runner Group
          run: |
            echo "Runner group used: ${{ matrix.runner-group }}"

```

It just spins at this point :

```
Run azure/login@v2
  with:
    creds: ***
    enable-AzPSSession: false
    environment: azurecloud
    allow-no-subscriptions: false
    audience: api://AzureADTokenExchange
    auth-type: SERVICE_PRINCIPAL
Clearing azure cli accounts from the local cache.
/usr/bin/az account clear
```
