### ISSUE TITLE
unable to access `node` and `yarn` within inlineScripts

### ISSUE THREAD

**Issue by Hotell** [Azure/cli#174]
invoking NodeJs tools form within inlineScripts doesn't work

- workflow definition: https://github.com/microsoft/fluentui/blob/master/.github/workflows/bundle-size-base.yml#L54

This is blocker for our migration to GHA efforts which is required within security directive.

### Repro

workflow example:

```yml
- name: Upload report
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            yarn monosize upload-report --branch=${{ github.ref }} --commit-sha ${{ github.sha }}
```

**Error:**

```
Starting script execution via docker image mcr.microsoft.com/azure-cli:latest
🚨 /home/runner/work/_temp/AZ_CLI_GITHUB_ACTION_17308423827.sh: line 1: yarn: command not found 🚨
Error: Error: az cli script failed.
```

Directly invoking nodejs binary

```
  inlineScript: |
            $GITHUB_WORKSPACE/node_modules/.bin/monosize upload-report --branch=${{ github.ref }} --commit-sha ${{ github.sha }}
```

**Error:**

```
Starting script execution via docker image mcr.microsoft.com/azure-cli:latest
🚨 /usr/bin/env: 'node': No such file or directory 🚨
Error: Error: az cli script failed.
```

**Comment by MoChilia** [comment]
Hi @Hotell, `nodejs` and `yarn` are not common dependencies for Azure CLI commands, so they are not included in the image of Azure/cli action by default, see https://github.com/Azure/azure-cli/blob/276868511174d2aea59ae0dcb78d5760aaea5e01/azure-linux.dockerfile#L11C80-L11C92. If you require them inside Azure/cli action, you can install them manually by 
```yaml
    - uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
           tdnf install nodejs npm -y
           npm install --global yarn
```
