### ISSUE TITLE
Does Azure CLI Action has access to GITHUB_WORKSPACE folder?

### ISSUE THREAD

**Issue by akisiel1** [Azure/cli#18]
Hi!

I'm using your Action to push my Helm package to ACR and have a problem which I cannot solve (and understand why it's happening in the first place).

My workflow:
1) Create a Helm Package
2) Login into Azure
2) Push it into ACR with Azure CLI command `az acr helm push`

My workflow yaml: 
```
   - name: Helm package
      run: 'helm package ${{ github.workspace }}/chart/${{ secrets.APP_NAME }}--version v${{ github.run_number }} --destination ${{ github.workspace }}/helm --app-version v${{ github.run_number }}'
 
   - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 

    - name: Push TO ACR
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az acr helm push ${{ github.workspace }}/helm/${{ secrets.APP_NAME }}-v${{ github.run_number }}.tgz --name ${{ secrets.ACR_NAME }} --force;
```

the result:
![image](https://user-images.githubusercontent.com/17008916/87031528-8a490680-c1e3-11ea-8fe4-11932e8cbaf0.png)
![image](https://user-images.githubusercontent.com/17008916/87031667-bd8b9580-c1e3-11ea-860e-95d4ff2b2b23.png)

Paths are exactly the same, the package seems to exists.

Can you tell me what I am doing wrong?
