### ISSUE TITLE
Action throws error: Unable to find image 'mcr.microsoft.com/azure-cli:2.19.1' locally

### ISSUE THREAD

**Issue by paschalidi** [Azure/cli#34]
Hey all. Thanks everyone for the very good work on all the azure related github actions. 
I am following this simple tutorial, in order to [host a static react website using gihube actions](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blobs-static-site-github-actions).

I am getting an error, right after the `inlineScript` is executed. The error returns
```
Error: Error: Unable to find image 'mcr.microsoft.com/azure-cli:2.19.1' locally
```
see also image bellow 
![image](https://user-images.githubusercontent.com/4181674/107961699-2c14ab00-6f9e-11eb-9eb9-f7c34b73b114.png)

My workflow gh action looks like this 
```
name: Deploy front webapp

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - develop

jobs:
  install:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: cd ./redi-connect-front && yarn install --frozen-lockfile

  build:
    runs-on: ubuntu-latest
    needs: [install]
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Build
        env:
          CI: "" # This needs to be true ideally however the app wont build because of some js errors
        run: cd ./redi-connect-front && yarn build:prod:berlin

      - uses: actions/upload-artifact@v2
        with:
          name: app-build
          path: |
            **/build
            !**/node_modules
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          azcliversion:  2.19.1
          inlineScript: |
            az storage blob upload-batch --account-name storagedevrediaduz -d '$web' -s ./redi-connect-front/build

      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          azcliversion: 2.19.1
          inlineScript: |
          az cdn endpoint purge --content-paths  "/*" --profile-name "cdnprofiledevrediaduz" --name cdn-endpoint-dev-redi-aduz" --resource-group "rg-dev-redi-aduz"

      # Azure logout
      - name: logout
        run: |
          az logout
```

Any ideas why this error coems up?
