### ISSUE TITLE
Not obtaining the latest AZ CLI version

### ISSUE THREAD

**Issue by Gordonby** [Azure/cli#52]
I'm getting the error
`Error: Please enter a valid azure cli version.  See available versions: https://github.com/Azure/azure-cli/releases.`

When specifying 
```yaml
      - name: What If
        uses: Azure/cli@1.0.4
        with:
          azcliversion: 2.28.1
```
I get the error above.
When I remove `azcliversion` the action installs version 2.28.0 of the Azure CLI

v2.28.1 was released 3 days ago.
![image](https://user-images.githubusercontent.com/17914476/136771741-8ccb449b-681b-4ec6-b059-b46f2383d612.png)
