### ISSUE TITLE
Error: bash: /_temp/AZ_CLI_GITHUB_ACTION_1642662288004.sh: No such file or directory

### ISSUE THREAD

**Issue by GopikaV24** [Azure/cli#69]
We are trying to run AzureCLI action in our GitHub self-hosted agent which is created in the  AKS cluster. We are getting the following issue,

![image](https://user-images.githubusercontent.com/60219629/150292142-aa8f51eb-539c-42ec-ae42-30e46adb7e5b.png)

Agent Image: ubuntu:20.04
AzureCLI version: 2.32.0

Not sure if anything was missed in configuration?

**Comment by t-dedah** [comment]
Hi @GopikaV24 this might happen if the file doesnt have executable permissions. You can confirm that using the following command. 
``` 
ls -l ./scripts/moveFiles.sh
```
Two methods to fix this:

1. Change file permissions before cli step

```yaml
    run: |
        chmod +x ./path_to_file/file_name.sh
```

2. directly add ‘sh’ before the command:
```yaml
    run: |
        sh ./path_to_file/file_name.sh
```

**Comment by GopikaV24** [comment]
Hi @t-dedah ,
I have tried to give permission before CLI action and inside CLI action also, getting the same issue.

![image](https://user-images.githubusercontent.com/60219629/150303890-167b8d53-f85c-4d4b-9838-e17cb24e9351.png)

We are getting this issue for inlinescript also.
```
     - name: Azure CLI script1
        uses: azure/CLI@v1
        with:
          inlineScript: |   
            az -v
```

**Comment by t-dedah** [comment]
@GopikaV24 Will it be possible to share the template so that we can replicate the issue?

**Comment by GopikaV24** [comment]
@t-dedah, By referring below mentioned repo we are creating a selfhosted image and POD in AKS Cluster.

GitHub Runner in Docker Reference: https://github.com/SanderKnape/github-runner

**Comment by GopikaV24** [comment]
Any updates?

**Comment by marcusradell** [comment]
I'm having the same issue when running shell scripts.
And I am calling chmod before executing the script.

**Comment by t-dedah** [comment]
Hi @GopikaV24 Can we also confirm if the file actually exists at the required location?

**Comment by MoChilia** [comment]
Hi, @GopikaV24! I want to know if you are still facing the issue. If yes, could you check whether the `AZ_CLI_GITHUB_ACTION_CurrentTime.sh` file is actually in the `_temp` directory by running `ls -la /_temp` in the `inlineScript` of Azure/cli? This file might fail to create for some reason.

**Comment by MoChilia** [comment]
For a long time with no activity, closing the issue now.  If there is any further question to discuss, please open a new issue.

**Comment by FlorentATo** [comment]
@MoChilia @t-dedah the permission issue on the script that is generated by azure/cli and source from `inlinescript`

I'm facing the same issue:
```yaml
    - name: Azure CLI script to copy artifact
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az storage blob upload --account-name REDACTED  --container-name REDACTED  --name target_file_name --file ${{inputs.file_path}}/${{inputs.file}} --auth-mode login
```
which results in:
```
(...)
Digest: sha256:38f8385bb27f9b6dabee3045852cabce2e9da7d4ed35d5783b4691a02489b4c2
Status: Downloaded newer image for mcr.microsoft.com/azure-cli:latest
bash: /data/runner/work/_temp/AZ_CLI_GITHUB_ACTION_1724706079140.sh: No such file or directory

cleaning up container...
MICROSOFT_AZURE_CLI_1724706078695_CONTAINER
```

There might be a condition were the action fails to create the script in `/data/runner/work/_temp/` but I would expect `createScriptFile` to fail if that was the case... I'm confused.
