### ISSUE TITLE
Azure CLI use_dynamic_install throws Unhandled promise rejection

### ISSUE THREAD

**Issue by briglx** [Azure/cli#72]
I'm trying to run code that requires the `az automation` extension. 

I'm calling `az config set extension.use_dynamic_install=yes_without_prompt`

Related Issue here https://github.com/Azure/azure-cli/issues/21505

```
- name: Clean Up Resources
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            
            # Allow Dynamic installation of extensions
            az config set extension.use_dynamic_install=yes_without_prompt
```
However it throws the following error:

```
UnhandledPromiseRejectionWarning: Error: az cli script failed.
    at /home/runner/work/_actions/azure/CLI/v1/dist/index.js:1:2[39](https://github.com/xxx/xxx/runs/5400826457?check_suite_focus=true#step:8:39)64
    at Generator.throw (<anonymous>)
    at rejected (/home/runner/work/_actions/azure/CLI/v1/dist/index.js:1:20436)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1861) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1861) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
