### ISSUE TITLE
"Unhandled promise rejection" error

### ISSUE THREAD

**Issue by tdevopsottawa** [Azure/cli#73]
I have a pretty simple Azure/cli step in my pipeline that's giving me the error:

```
(node:3210) UnhandledPromiseRejectionWarning: Error: az cli script failed.
    at /home/runner/work/_actions/azure/CLI/v1/dist/index.js:1:23964
    at Generator.throw (<anonymous>)
    at rejected (/home/runner/work/_actions/azure/CLI/v1/dist/index.js:1:20436)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:3210) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3210) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This is the task code:

```
      - name: Dewhitelist IP
        if: always()
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az acr network-rule remove --name retailde --ip-address ${{steps.runner_ip.outputs.runnerip}}
```
