### ISSUE TITLE
az & azure-cli-ml extension for deploying model

### ISSUE THREAD

**Issue by sergey-ivanchuk** [Azure/cli#82]
Hi,

I'm roughly following this setup here - https://github.com/marketplace/actions/azure-cli-action

Here's my Github action setup --

```yaml
name: deploy

on: [push]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script file
      uses: azure/CLI@v1
      env:
        TENANT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}
        CLIENT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}
        CLIENT_SECRET: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az extension add --name azure-cli-ml
          az login --service-principal --username="${CLIENT_ID}" --password="${CLIENT_SECRET}" --tenant="${TENANT_ID}"
          az acr login --name <>.azurecr.io

          cd $GITHUB_WORKSPACE/deployment

          az ml model deploy --ct <>  --model <>
```

Error messages gets triggered in the last line around `az ml model deploy `, and here's the core feedback:

```text
ERROR: An error occurred: DOCKER_COMMAND_ERROR
Please verify if Docker client is installed and running.
Error: Error: az cli script failed.
cleaning up container...
MICROSOFT_AZURE_CLI_1662163098469_CONTAINER
```

Would anything be suggested to easily start-up and run a Docker client (daemon). Seems like I need to have Docker running, but also I will need to have `uses: azure/CLI@v1`
