### ISSUE TITLE
"Invalid reference format" error

### ISSUE THREAD

**Issue by tdevopsottawa** [Azure/cli#93]
Attempting to use Azure CLI in a GitHub action using the official GitHub actions CLI to whitelist an IP address through the ACR firewall, with the following code:
```
      - name: Whitelist Runner IP
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az acr network-rule add --name retailde --ip-address <redacted>
```
results in: `Error: Error: docker: invalid reference format.`

This action was working flawlessly for months and then suddenly stopped working.
