### ISSUE TITLE
Issue Running az cli inline command on windows agent

### ISSUE THREAD

**Issue by totalitydevelopment** [Azure/cli#97]
I have task working fine on an Ubuntu agent as per:
```
some-task:
    runs-on: ubuntu-latest
    steps:
     - name: Do something
        uses: azure/CLI@v1
        with:
          azcliversion: 2.40.0
          inlineScript: az apim api ....etc
```

When trying the following however:
```
build:
    runs-on: windows-latest
    environment: Development
    steps:

      - name: Do something
        uses: azure/CLI@v1
        with:
           azcliversion: 2.40.0
           inlineScript: call az somecall....

```

I am receiving the error:
`Error: Please use Linux based OS as a runner.`

The documentation isn't quite clear for me:
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-cli-v1?view=azure-pipelines

Suggests just adding "call" as I have done.
