### ISSUE TITLE
The action not yet support Windows Runner

### ISSUE THREAD

**Issue by thohng** [Azure/cli#99]
For those need to run `az cli` on Windows Agent/Runner, we just used the alternative batch script/powershell script

```
- name: Azure login
  if: ${{ success() }}
  uses: azure/login@v1
  with:
    creds: ${{ secrets.AZURE_CREDENTIALS }}

- name: Test show Azure login
  if: ${{ success() }}
  run: az account show

- name: Upload to blob storage
  if: ${{ success() }}
  run: az storage blob upload-batch --auth-mode login --account-name storageaccount --destination containerid --destination-path path --source source --pattern *.zip --overwrite --no-progress
```

https://github.com/Azure/cli/blob/548c3ec692451811afd4a68a596eec087ecfc434/src/main.ts#L19-L22

#54 Why is the Azure CLI action only available on Linux based runners?

#97 Issue Running az cli inline command on windows agent
